export const funnyDescriptions = [
  "La IA está cocinando las mejores ideas para ti...",
  "Nuestra IA está tomando un pequeño refrigerio, ¡volverá enseguida!",
  "La IA está meditando profundamente sobre tu solicitud...",
  "Cuidado, ¡nuestra IA está a punto de deslumbrarte con su magia!",
  "Un momento, la IA está consultando con sus amigos robots...",
  "La IA está buscando su café antes de continuar...",
  "La IA está contando bits para relajarse...",
  "Procesando... pero con mucho estilo",
  "La IA está cargando chistes malos... por favor espera.",
  "Un segundo, la IA está resolviendo un cubo Rubik en la nube.",
  "La IA está alimentando a sus algoritmos mascota",
  "Cuidado, la IA está soñando con ovejas binarias",
  "Nuestra IA está haciendo yoga digital para concentrarse.",
  "La IA está ajustando sus circuitos con un poco de música lo-fi",
  "La IA está repasando sus memes favoritos para inspirarse.",
  "Revisando que todos los 0 y 1 estén en orden",
  "La IA está debatiendo con ChatGPT sobre quién piensa más rápido.",
  "Cargando... ¿o tal vez filosofando?",
  "La IA está practicando su mejor 'beep boop' de robot.",
  "La IA está revisando el manual secreto de la Matrix.",
  "Recopilando sabiduría ancestral de los disquetes olvidados",
  "La IA está preguntándole a Google cómo impresionarte.",
  "La IA se tomó un break... está programando un café",
  "Calibrando su sentido del humor antes de responder",
  "La IA está ordenando sus emojis favoritos",
  "Probando qué tan rápido puede correr en la nube",
  "Haciendo scroll infinito en Internet... solo por diversión.",
  "Verificando si los aliens ya subieron algo nuevo a la red",
  "La IA está ajustando la gravedad en su simulación personal.",
  "Calculando la probabilidad de que le caigas bien",
  "La IA está tomando un curso online de chistes para robots.",
  "Desfragmentando sus pensamientos... paciencia por favor.",
  "La IA está enviando señales secretas a otro universo.",
];
