export * from './DocumentFile';
export * from './Education';
export * from './Experience';
export * from './Feedback';
export * from './Language';
export * from './TechnicalSkill';
export * from './SoftSkill';
export * from './Talent';
export * from './TalentDetails';